CREATE TABLE EPIS.MASOFFICER 
 (
	OFFICERID BIGINT NOT NULL AUTO_INCREMENT,
	PRINCIPALID BIGINT, 
	SESSIONID BIGINT, 
	USERNAME VARCHAR(40),
	OFFICERCODE VARCHAR(50), 
	OFFICERGIVENNAME VARCHAR(200), 
	OFFICERFAMILYNAME VARCHAR(200), 
	PERMISSION VARCHAR(50), 
	ISPOSITIVE BIGINT, 
	DESCRIPTION VARCHAR(200), 
	UPDATEDTTM TIMESTAMP (6), 
	UPDATESYSTEM CHAR(3), 
	UPDATEUSER VARCHAR(32), 
	VERSIONSTAMP BIGINT, 
	VERIFY_FLAG CHAR(1), 
	VERIFY_KEY VARCHAR(64), PASSWORD VARCHAR(64), PRIMARY KEY (OFFICERID)
);
--------------------------------------------------------
--  DDL for Table ARCUSERAUTHNTICN
--------------------------------------------------------
CREATE TABLE EPIS.ARCUSERAUTHNTICN 
 (
	USERAUTHNTICNID BIGINT NOT NULL AUTO_INCREMENT,
	OFFICERID BIGINT, PASSWORD VARCHAR(64), 
	UPDATEDTTM DATE, 
	UPDATESYSTEM CHAR(3), 
	UPDATEUSER VARCHAR(32), 
	VERSIONSTAMP BIGINT, PRIMARY KEY (USERAUTHNTICNID)
);
CREATE TABLE EPIS.ARCPRINCIPAL 
 (
	PRINCIPALID BIGINT NOT NULL AUTO_INCREMENT, 
	NAME VARCHAR(64), 
	DESCRIPTION VARCHAR(200), 
	UPDATEDTTM TIMESTAMP(6), 
	UPDATESYSTEM CHAR(3), 
	UPDATEUSER VARCHAR(32), 
	VERSIONSTAMP BIGINT, PRIMARY KEY (PRINCIPALID)
)
INSERT INTO EPIS.MASOFFICER (PRINCIPALID,SESSIONID,USERNAME,OFFICERCODE,OFFICERGIVENNAME,OFFICERFAMILYNAME,PERMISSION,ISPOSITIVE,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP,VERIFY_FLAG,VERIFY_KEY, PASSWORD) VALUES (10,1692,'EPIS15','EPIS15','Mena','Chanda', NULL,1, NULL, NULL, NULL, NULL, NULL,'Y','e10adc3949ba59abbe56e057f20f883e','5f4dcc3b5aa765d61d8327deb882cf99');
INSERT INTO EPIS.ARCUSERAUTHNTICN (OFFICERID, PASSWORD,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES (1,'5f4dcc3b5aa765d61d8327deb882cf99', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('test6','test6', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('TRANSFER','user back ???????????????-????????????? ??.', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('test22','aaa33', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('test','c', NULL, NULL,'EPIS3', NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('test3','test3', NULL, NULL,'EPIS3', NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('Suppervisor','Suppervisor', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('TRANSIN','user back ??????????????? ??.', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('ADMIN','desc', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('BASIC','Allow to approve transactions', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('AGENT','Allow to do payment transactions', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('CUSTOMERSERVICE','desc', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('CALLCENTER','desc', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('USERAGENT','desc', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('GFMISAGENT','Allow GFMIS transactions', NULL, NULL, NULL, NULL);
INSERT INTO EPIS.ARCPRINCIPAL (NAME,DESCRIPTION,UPDATEDTTM,UPDATESYSTEM,UPDATEUSER,VERSIONSTAMP) VALUES ('BACKOFFICE','???????????? ???????? ??? ??????', NULL, NULL, NULL, NULL);
CREATE TABLE EPIS.DEDUCTION_MANUAL 
 (
	DEDUCTION_MANUAL_ID BIGINT NOT NULL AUTO_INCREMENT,
	DEDUCTIONNO VARCHAR(40),
	DEDUCTIONTYPE VARCHAR(10),
	AMOUNT DECIMAL(14,4),
	PAYMENTDATE DATE,
	UPDATEDTTM TIMESTAMP(6),
	UPDATESYSTEM CHAR(3),
	UPDATEUSER VARCHAR(32),
	VERSIONSTAMP BIGINT,
	INVOICE_NO VARCHAR(30),
	REMARK VARCHAR(100),
	CREATE_BY VARCHAR(20),
	CREATE_DATE TIMESTAMP(6),
	UPDATE_BY VARCHAR(20),
	UPDATE_DATE TIMESTAMP(6),
	RECORD_STATUS VARCHAR(20),
	MANUAL_ID BIGINT, PRIMARY KEY (DEDUCTION_MANUAL_ID)
);
CREATE TABLE EPIS.CORRECEIPTDOCUMENT 
 (
	RECEIPTDOCUMENTID BIGINT NOT NULL AUTO_INCREMENT,
	RECEIPTDOCUMENTTYPE VARCHAR(10),
	RECEIPTHEADER VARCHAR(5),
	BRANCHAREA VARCHAR(10),
	DATETEXT VARCHAR(20),
	DOCUMENTCOUNT BIGINT, PRIMARY KEY (RECEIPTDOCUMENTID)
)
CREATE TABLE EPIS.PAYMENT_MANUAL 
(
	MANUAL_ID BIGINT NOT NULL AUTO_INCREMENT,
	PAYMENT_ID BIGINT,
	INVOICE_NO VARCHAR(30),
	RECEIPT_NO_MANUAL VARCHAR(30),
	PAID_DATE TIMESTAMP(6),
	BRANCH_AREA VARCHAR(100),
	BRANCH_CODE VARCHAR(20),
	PAID_AMOUNT DECIMAL(14,4),
	SOURCE VARCHAR(20),
	CLEARING VARCHAR(20),
	REMARK VARCHAR(50),
	CREATE_BY VARCHAR(20),
	CREATE_DATE TIMESTAMP(6),
	UPDATE_BY VARCHAR(20),
	UPDATE_DATE TIMESTAMP(6),
	RECORD_STATUS VARCHAR(20),
	REF_ID BIGINT,
	ACCOUNT_NO VARCHAR(35),
	CLEARING_SAP VARCHAR(20), PRIMARY KEY (MANUAL_ID)
)
CREATE TABLE EPIS.MASTER_RECEIPT_HEADER_MAPPING 
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	RECEIPT_HEADER_MAPPING VARCHAR(50),
	RECEIPT_HEADER VARCHAR(50),
	REMARK VARCHAR(100),
	CREATE_DATE TIMESTAMP(6),
	CREATE_BY VARCHAR(100),
	UPDATE_DATE TIMESTAMP(6),
	UPDATE_BY VARCHAR(100),
	RECORD_STATUS VARCHAR(20), PRIMARY KEY (ID)
)
CREATE TABLE EPIS.PAYMENT_INVOICE_MANUAL 
(  
 `PAYMENT_INVOICE_MANUAL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MANUAL_ID` bigint(20) DEFAULT NULL,
  `SOURCE` varchar(30) DEFAULT NULL,
  `INVOICE_NO` varchar(30) DEFAULT NULL,
  `BEFOR_VAT` decimal(14,4) DEFAULT NULL,
  `VAT_AMOUNT` decimal(14,4) DEFAULT NULL,
  `AMOUNT` decimal(14,4) DEFAULT NULL,
  `VAT_RATE` int(11) DEFAULT NULL,
  `CUSTOMER_NAME` varchar(300) DEFAULT NULL,
  `CUSTOMER_ADDRESS` varchar(300) DEFAULT NULL,
  `CUSTOMER_SEGMENT` varchar(300) DEFAULT NULL,
  `CUSTOMER_BRANCH` varchar(300) DEFAULT NULL,
  `TAXNO` varchar(25) DEFAULT NULL,
  `SUB_NO` varchar(25) DEFAULT NULL,
  `PERIOD` varchar(20) DEFAULT NULL,
  `SERVICE_TYPE` varchar(45) DEFAULT NULL,
  `CLEARING` varchar(20) DEFAULT NULL,
  `PRINT_RECEIPT` varchar(20) DEFAULT NULL,
  `REMARK` varchar(100) DEFAULT NULL,
  `CREATE_BY` varchar(20) DEFAULT NULL,
  `CREATE_DATE` timestamp(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `UPDATE_BY` varchar(20) DEFAULT NULL,
  `UPDATE_DATE` timestamp(6) NOT NULL DEFAULT '0000-00-00 00:00:00.000000',
  `RECORD_STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`PAYMENT_INVOICE_MANUAL_ID`)
)
CREATE TABLE EPIS.TRSCREDITREF_MANUAL 
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CREDITNO VARCHAR(40),
	PUBLISHERDEC VARCHAR(20),
	CARDTYPE VARCHAR(20),
	AMOUNT DECIMAL(14,2),
	UPDATEDTTM TIMESTAMP(6),
	UPDATESYSTEM CHAR(3),
	UPDATEUSER VARCHAR(32),
	VERSIONSTAMP DECIMAL,
	METHOD_MANUAL_ID BIGINT, PRIMARY KEY (ID)
)
CREATE TABLE EPIS.TRSCHEQUEREF_MANUAL 
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CHEQUENO VARCHAR(40),
	PUBLISHERID VARCHAR(20),
	PUBLISHER VARCHAR(300),
	BRANCH VARCHAR(300),
	AMOUNT DECIMAL(14,2),
	UPDATEDTTM TIMESTAMP(6),
	UPDATESYSTEM CHAR(3),
	UPDATEUSER VARCHAR(32),
	VERSIONSTAMP BIGINT,
	CHEQUEDATE TIMESTAMP(6),
	BOUNCE_CHEQUE_DATE TIMESTAMP(6),
	REVERSE_AR_DATE TIMESTAMP(6),
	BOUNCE_STATUS VARCHAR(20),
	METHOD_MANUAL_ID BIGINT, PRIMARY KEY (ID)
)
CREATE TABLE EPIS.TRSMETHOD_MANUAL 
(
	METHOD_MANUAL_ID BIGINT NOT NULL AUTO_INCREMENT,
	CODE VARCHAR(13),
	NAME VARCHAR(200),
	CHEQUENO VARCHAR(40),
	ACCOUNTNO VARCHAR(40),
	AMOUNT DECIMAL(14,4),
	UPDATEDTTM TIMESTAMP(6),
	UPDATESYSTEM CHAR(3),
	UPDATEUSER VARCHAR(32),
	VERSIONSTAMP BIGINT,
	OFFSET_DOCUMENT_NO VARCHAR(255),
	OFFSET_ACCOUNT_CODE VARCHAR(255),
	OFFSET_ACCOUNT_NAME VARCHAR(255),
	REMARK VARCHAR(100),
	CREATE_BY VARCHAR(20),
	CREATE_DATE TIMESTAMP(6),
	UPDATE_BY VARCHAR(20),
	UPDATE_DATE TIMESTAMP(6),
	RECORD_STATUS VARCHAR(20),
	MANUAL_ID BIGINT, PRIMARY KEY (METHOD_MANUAL_ID)
)



